CREATE TABLE Part(
    Nr UUID NOT NULL PRIMARY KEY,
    Name VARCHAR(100) NOT NULL,
    Price NUMERIC(8,2)
    );

CREATE TABLE Worker(
    Id UUID NOT NULL PRIMARY KEY,
    Name VARCHAR(100) NOT NULL
    );